drop table if exists twitter.follow;
create table twitter.follow
(
    twitter_follow_id bigint
        generated by default as identity
        primary key,

    follow_fetch_id bigint
        not null
        references twitter.follow_fetch
        deferrable initially immediate,

    source_user_id bigint
        not null
        references twitter.user
        deferrable initially immediate,

    target_user_id bigint
        not null
        references twitter.user
        deferrable initially immediate,

    insert_dt timestamptz not null default now(),

    unique(follow_fetch_id, source_user_id, target_user_id)
);
create unique index on twitter.follow using btree
    (follow_fetch_id, target_user_id, source_user_id);


